import React from 'react'
import { toast } from '../components/Toast.jsx'
import { Header } from '../components/AppShell.jsx'
import { AppFooter } from '../components/Shared.jsx'
import Pill from '../components/Pill.jsx'
import Icon from '../components/Icon.jsx'
import { reports, STATUS_META } from '../data.js'

export default function Reports() {
  return (
    <>
      <Header
        eyebrow="Archive & Review"
        title="Reports"
        subtitle="Engineer-reviewed compliance assessments generated by ChattamAI"
        action={
          <button onClick={() => toast('Export queued — generates a compiled PDF of the selected assessment.', 'ok')} className="accent-gradient px-4 py-2 rounded text-sm font-semibold text-black flex items-center gap-2 hover:brightness-110">
            <Icon name="download" /> Export PDF
          </button>
        }
      />
      <div className="p-6 md:p-8 space-y-6">
        <div className="bg-[#10151C] border border-[#222C3A] rounded shadow-lg overflow-hidden">
          <div className="px-6 py-4 border-b border-[#222C3A] bg-[#161D27]/50">
            <h3 className="text-sm font-semibold text-white tracking-wide uppercase flex items-center gap-2"><Icon name="archive" className="text-[#22D3EE]" /> Assessment History</h3>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full min-w-[820px]">
              <thead>
                <tr className="border-b border-[#222C3A] bg-[#0C1117]">
                  {['Project', 'Date', 'Overall Result', 'Violations', 'Engineer Review', 'Export'].map((h, i) => (
                    <th key={h} className={`px-6 py-3 text-[11px] mono text-[#5B6879] uppercase tracking-wider font-medium ${i === 5 ? 'text-right' : 'text-left'}`}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-[#222C3A]">
                {reports.map((r) => {
                  const s = STATUS_META[r.status]
                  return (
                    <tr key={r.project} className="hover:bg-[#161D27] transition-colors group">
                      <td className="px-6 py-4 text-sm text-white">{r.project}</td>
                      <td className="px-6 py-4 text-xs mono text-[#5B6879]">{r.date}</td>
                      <td className="px-6 py-4"><Pill kind={s.pill}>{s.label}</Pill></td>
                      <td className="px-6 py-4 text-sm mono" style={{ color: r.violations === null ? 'var(--text-3)' : r.violations > 0 ? s.color : 'var(--ok)' }}>{r.violations === null ? '—' : r.violations}</td>
                      <td className="px-6 py-4 text-xs text-[#9AA7B6]">{r.reviewer}</td>
                      <td className="px-6 py-4 text-right">
                        <button onClick={() => toast(`Exporting “${r.project}” as PDF…`, 'ok')} className="text-[11px] mono text-[#22D3EE] inline-flex items-center gap-1 hover:underline">
                          <Icon name="file-down" /> PDF ↓
                        </button>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        </div>
        <div className="flex items-start gap-2 text-[11px] mono text-[#5B6879]">
          <Icon name="info" className="text-amber-500/60 flex-shrink-0 mt-0.5" />
          Reports are AI-assisted assessments — final decisions rest with the reviewing engineer.
        </div>
      </div>
      <AppFooter extra="PDF Generator v2.1" />
    </>
  )
}
